name: Weekly Lighthouse Audit

on:
  schedule:
    - cron: '0 12 * * 5'  # Every Friday at 12pm UTC = 8am Eastern
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: |
        npm install -g lighthouse
        npm install csv-writer fs

    - name: Run Lighthouse and Generate JSON Reports
      run: |
        mkdir lighthouse-reports
        mkdir json-summaries
        while IFS= read -r url
        do
          name=$(echo $url | sed 's|https\?://||; s|/|_|g')
          lighthouse "$url" --output json --output-path="json-summaries/${name}.json" --chrome-flags="--headless"
        done < urls.txt

    - name: Create Summary CSV from JSON
      run: |
        node <<EOF
        const fs = require('fs');
        const path = require('path');
        const createCsvWriter = require('csv-writer').createObjectCsvWriter;

        const dir = 'json-summaries';
        const files = fs.readdirSync(dir);
        const records = [];
        const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

        files.forEach(file => {
          const data = JSON.parse(fs.readFileSync(path.join(dir, file)));
          const url = data.finalUrl;
          const categories = data.categories;
          records.push({
            Website: url,
            Performance: Math.round(categories.performance.score * 100),
            Accessibility: Math.round(categories.accessibility.score * 100),
            BestPractices: Math.round(categories['best-practices'].score * 100),
            SEO: Math.round(categories.seo.score * 100),
            Date: today
          });
        });

        const csvWriter = createCsvWriter({
          path: \`lighthouse-reports/summary_\${today}.csv\`,
          header: [
            {id: 'Website', title: 'Website'},
            {id: 'Performance', title: 'Performance'},
            {id: 'Accessibility', title: 'Accessibility'},
            {id: 'BestPractices', title: 'Best Practices'},
            {id: 'SEO', title: 'SEO'},
            {id: 'Date', title: 'Date'}
          ]
        });

        csvWriter.writeRecords(records).then(() => console.log('CSV with date written.'));
        EOF

    - name: Upload summary CSV only
      uses: actions/upload-artifact@v4
      with:
        name: lighthouse-summary
        path: lighthouse-reports/summary_*.csv
